export const USER_ROLES = {
  ORG_ADMIN: 'ORG_ADMIN',
  CLINICAL_DIRECTOR: 'CLINICAL_DIRECTOR',
  BCBA: 'BCBA',
  RBT: 'RBT',
  BT: 'BT',
  HR_MANAGER: 'HR_MANAGER',
} as const

export const PATIENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISCHARGED: 'DISCHARGED',
  ON_HOLD: 'ON_HOLD',
} as const

export const PLAN_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_BCBA_REVIEW: 'PENDING_BCBA_REVIEW',
  PENDING_CLINICAL_DIRECTOR: 'PENDING_CLINICAL_DIRECTOR',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  REJECTED: 'REJECTED',
} as const

export const SUBSCRIPTION_PLANS = {
  STARTER: 'STARTER',
  PROFESSIONAL: 'PROFESSIONAL',
  ENTERPRISE: 'ENTERPRISE',
} as const

export const REVIEW_TYPES = {
  DRAFT_REVIEW: 'DRAFT_REVIEW',
  CLINICAL_REVIEW: 'CLINICAL_REVIEW',
  COMPLIANCE_REVIEW: 'COMPLIANCE_REVIEW',
} as const

export const NOTIFICATION_TYPES = {
  TREATMENT_PLAN_REVIEW: 'TREATMENT_PLAN_REVIEW',
  TREATMENT_PLAN_APPROVED: 'TREATMENT_PLAN_APPROVED',
  TREATMENT_PLAN_REJECTED: 'TREATMENT_PLAN_REJECTED',
  CERTIFICATION_EXPIRING: 'CERTIFICATION_EXPIRING',
  PLAN_EXPIRING: 'PLAN_EXPIRING',
  PATIENT_ASSIGNMENT: 'PATIENT_ASSIGNMENT',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
} as const

export type UserRole = keyof typeof USER_ROLES
export type PatientStatus = keyof typeof PATIENT_STATUS
export type PlanStatus = keyof typeof PLAN_STATUS
export type SubscriptionPlan = keyof typeof SUBSCRIPTION_PLANS
export type ReviewType = keyof typeof REVIEW_TYPES
export type NotificationType = keyof typeof NOTIFICATION_TYPES
